### ISSUE TITLE
 validate_inclusion_of for enum field not working

### ISSUE THREAD

**Issue by Ana06** [thoughtbot/shoulda-matchers#1039]
I have the following code in my model:

``` Ruby
enum kiwi_type: %i[bootstrap delete docker image iso lxc oem pxe split testsuite vmx], _prefix: :type

validates :kiwi_type, presence: true, inclusion: { in: kiwi_types.keys }
```

and in my model test:
``` Ruby
it { is_expected.to validate_inclusion_of(:kiwi_type).in_array(Kiwi::PackageGroup.kiwi_types.keys) }
```

When running the test I get:

```
Failures:

  1) Kiwi::PackageGroup should validate that :kiwi_type is either ‹"bootstrap"›, ‹"delete"›, ‹"docker"›, ‹"image"›, ‹"iso"›, ‹"lxc"›, ‹"oem"›, ‹"pxe"›, ‹"split"›, ‹"testsuite"›, or ‹"vmx"›
     Failure/Error: it { is_expected.to validate_inclusion_of(:kiwi_type).in_array(Kiwi::PackageGroup.kiwi_types.keys) }
     
     ArgumentError:
       '123456789' is not a valid kiwi_type
     # ./spec/models/kiwi/package_group_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

Seems to be a bug, or maybe I am doing something wrong :thinking: 

I am using _shoulda-matchers-3.1.1_.
