### ISSUE TITLE
validate_uniqueness_of with multiple scopes results in ActiveRecord::InvalidForeignKey

### ISSUE THREAD

**Issue by thoraxe** [thoughtbot/shoulda-matchers#1313]
A model:
```ruby
class RelevanceLabel < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :filter
  belongs_to :article

  validates :article_id, uniqueness: { scope: [:user_id, :project_id, :filter_id] }
end
```

A test:
```ruby
  context 'validations' do

    before do
      # localhost is needed for elasticsearch
      # can probably titrate this down
      WebMock.disable_net_connect!(allow_localhost: true)

      # set sidekiq to inline
      require 'sidekiq/testing'
      Sidekiq::Testing.inline!

      @user = User.create(email: 'test@test.com',
                          password: 'password',
                          password_confirmation: 'password')
      @user.skip_confirmation!
      @user.save!
      # need a datasource for the articles
      # TODO: webmock doesn't seem to intercept superfeedr rack stuff
      allow_any_instance_of(DataSource).to receive(:subscribe).and_return(true)
      @source = DataSource.create(url: 'http://test.com/feed/', name: 'Test', slug: 'test')

      # need a project
      @labeling_project = FactoryBot.create(:project,
                                            notifications_enabled: false,
                                            user: @user)

      # need a query to use for the filter
      @query = Faker::Appliance.brand

      # need a stream
      @labeling_stream = FactoryBot.create(:filter,
                                           notifications_enabled: false,
                                           query: @query,
                                           user: @user,
                                           project: @labeling_project)

      @article =
        FactoryBot.create(:article,
                          data_source: @source,
                          content: Faker::Lorem.paragraph + " #{@query}")
    end

    it { should validate_uniqueness_of(:article_id).scoped_to([:user_id, :project_id, :filter_id]) }
  end
```

A test run:
```
oot@c18df30d6d22:/usr/src/app# bundle exec rspec spec/models/relevance_label_spec.rb:17
database: seraph_aa_test
Run options: include {:locations=>{"./spec/models/relevance_label_spec.rb"=>[17]}}
F

Failures:

  1) RelevanceLabel validations is expected to validate that :article_id is case-sensitively unique within the scope of :user_id, :project_id, and :filter_id                                                                                
     Failure/Error: it { should validate_uniqueness_of(:article_id).scoped_to([:user_id, :project_id, :filter_id]) }

     ActiveRecord::InvalidForeignKey:
       PG::ForeignKeyViolation: ERROR:  insert or update on table "relevance_labels" violates foreign key constraint "fk_rails_727680ea49"                                                                                                   
       DETAIL:  Key (article_id)=(0) is not present in table "articles".
       : UPDATE "relevance_labels" SET "article_id" = $1, "updated_at" = $2 WHERE "relevance_labels"."id" = $3
     # /usr/local/bundle/gems/airbrake-6.3.0/lib/airbrake/rails/active_record.rb:22:in `run_callbacks'
     # /usr/local/bundle/gems/airbrake-6.3.0/lib/airbrake/rails/active_record.rb:22:in `run_callbacks'
     # /usr/local/bundle/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:552:in `update_existing_record!'                                                                                   
     # /usr/local/bundle/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:674:in `matches_uniqueness_without_scopes?'                                                                        
     # /usr/local/bundle/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:330:in `matches?'                                                                                                  
     # ./spec/models/relevance_label_spec.rb:59:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:48:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/database_cleaner-1.8.4/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.8.4/lib/database_cleaner/configuration.rb:87:in `block (2 levels) in cleaning'                                                                                                              
     # /usr/local/bundle/gems/database_cleaner-1.8.4/lib/database_cleaner/configuration.rb:88:in `cleaning'
     # ./spec/rails_helper.rb:47:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::ForeignKeyViolation:
     #   ERROR:  insert or update on table "relevance_labels" violates foreign key constraint "fk_rails_727680ea49"
     #   DETAIL:  Key (article_id)=(0) is not present in table "articles".
     #   /usr/local/bundle/gems/airbrake-6.3.0/lib/airbrake/rails/active_record.rb:22:in `run_callbacks'
```

I am not sure if this is user error. Creating two RelevanceLabel objects with the same foreign keys results in the correct behavior (it doesn't work):

```
main)> RelevanceLabel.create(user: @user, project: @project, filter: @stream, article: @article, relevant: false)                                                                                                                           
   (0.1ms)  BEGIN
  RelevanceLabel Exists (0.5ms)  SELECT  1 AS one FROM "relevance_labels" WHERE "relevance_labels"."article_id" = $1 AND "relevance_labels"."user_id" = $2 AND "relevance_labels"."project_id" = $3 AND "relevance_labels"."filter_id" = $4 LIMIT $5  [["article_id", 9], ["user_id", 1], ["project_id", 3], ["filter_id", 2], ["LIMIT", 1]]
  RelevanceLabel Create (0.6ms)  INSERT INTO "relevance_labels" ("relevant", "user_id", "project_id", "filter_id", "article_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["relevant", false], ["user_id", 1], ["project_id", 3], ["filter_id", 2], ["article_id", 9], ["created_at", "2020-07-03 16:25:55.739678"], ["updated_at", "2020-07-03 16:25:55.739678"]]                                                                                 
   (0.6ms)  COMMIT
=> #<RelevanceLabel:0x00005600698a8468
 id: 7,
 relevant: false,
 predicted: nil,
 probability: nil,
 user_id: 1,
 project_id: 3,
 filter_id: 2,
 article_id: 9,
 created_at: Fri, 03 Jul 2020 16:25:55 UTC +00:00,
 updated_at: Fri, 03 Jul 2020 16:25:55 UTC +00:00>
(main)>
(main)>
(main)> RelevanceLabel.create(user: @user, project: @project, filter: @stream, article: @article, relevant: false)
   (0.1ms)  BEGIN
  RelevanceLabel Exists (0.2ms)  SELECT  1 AS one FROM "relevance_labels" WHERE "relevance_labels"."article_id" = $1 AND "relevance_labels"."user_id" = $2 AND "relevance_labels"."project_id" = $3 AND "relevance_labels"."filter_id" = $4 LIMIT $5  [["article_id", 9], ["user_id", 1], ["project_id", 3], ["filter_id", 2], ["LIMIT", 1]]
   (0.1ms)  ROLLBACK
=> #<RelevanceLabel:0x0000560065b5d770 id: nil, relevant: false, predicted: nil, probability: nil, user_id: 1, project_id: 3, filter_id: 2, article_id: 9, created_at: nil, updated_at: nil>
```

But, I definitely could be doing something wrong. I'd bet that over a bug in Shoulda.
