### ISSUE TITLE
shoulda-matchers not detected in Padrino using ActiveRecord 4

### ISSUE THREAD

**Issue by fj** [thoughtbot/shoulda-matchers#395]
I made a new Padrino project, added `shoulda-matchers` to my Gemfile under the test group, and generated a new simple User model:

``` ruby
ψ cat app/models/user.rb 
require 'active_record'

class User < ActiveRecord::Base
  validates :email, :presence => true
  validates :encrypted_password, :presence => true
end
```

When I run rspec, I get:

```
Failures:

  1) User validations 
     Failure/Error: it { should validate_presence_of(:email) }
     NoMethodError:
       undefined method `validate_presence_of' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1:0x007fe3336d97f0>
     # ./spec/models/user_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ./spec/environment_spec_helper.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/environment_spec_helper.rb:15:in `block (2 levels) in <top (required)>'
```

My gems are:

```
ψ gem list

*** LOCAL GEMS ***

activemodel (4.0.1)
activerecord (4.0.1)
activerecord-deprecated_finders (1.0.3)
activesupport (4.0.1)
arel (4.0.1)
atomic (1.1.14)
bigdecimal (1.2.0)
builder (3.1.4)
bundler (1.3.5)
diff-lcs (1.2.5)
http_router (0.11.0)
i18n (0.6.5)
io-console (0.4.2)
json (1.7.7)
mail (2.5.4)
mime-types (1.25.1)
minitest (4.7.5, 4.3.2)
moneta (0.7.20)
multi_json (1.8.2)
pg (0.17.0)
polyglot (0.3.3)
psych (2.0.0)
rack (1.5.2)
rack-protection (1.5.1)
rack-test (0.6.2)
rake (10.1.0, 0.9.6)
rdoc (4.0.0)
rspec (2.14.1)
rspec-core (2.14.7)
rspec-expectations (2.14.4)
rspec-mocks (2.14.4)
shoulda-matchers (2.4.0)
sinatra (1.4.4)
slim (2.0.2)
temple (0.6.7)
test-unit (2.0.0.0)
thor (0.17.0)
thread_safe (0.1.3)
tilt (1.4.1)
treetop (1.4.15)
tzinfo (0.3.38)
url_mount (0.2.1)
```

and my Gemfile is:

```
ψ cat Gemfile
source 'https://rubygems.org'

gem 'rake'
gem 'slim'
gem 'activerecord', :require => 'active_record'
gem 'pg'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'shoulda-matchers'
end

gem 'padrino', :git => "git://github.com/padrino/padrino-framework.git"
```
