### ISSUE TITLE
validate_confirmation_of and internationalization

### ISSUE THREAD

**Issue by mpugach** [thoughtbot/shoulda-matchers#593]
Hi.

I experience the following issue:

```
Failure/Error: Then { is_expected.to validate_confirmation_of(:password) }
   Expected errors to include "doesn't match Пароль" when password is set to "different value", got errors: ["повинно бути таким самим як і пароль (attribute: \"password_confirmation\", value: \"some value\")"]
```

`length` is validated also and errors are localized, but `ensure_length_of` behaves like it should.

For example:

```
Failure/Error: Then  { is_expected.to ensure_length_of(:password).is_at_least(5) }
   Expected errors to include "занадто короткий (мінімум 5 символів)" when password is set to "xxxx", got errors: ["занадто короткий (мінімум 6 символів) (attribute: \"password\", value: \"xxxx\")"]
```

my locale file:

``` YAML
uk:
  activerecord:
    attributes:
      person:
        password:               'Пароль'
        password_confirmation:  'Підтвердження'
    errors:
      models:
        person:
          password:
            too_short:            'занадто короткий (мінімум %{count} символів)'
          password_confirmation:
            confirmation:         'повинно бути таким самим як і пароль'
```

Is it a bug?
