### ISSUE TITLE
Issue with Shoulda::Matchers::ActiveRecord::Uniqueness::TestModels

### ISSUE THREAD

**Issue by fabn** [thoughtbot/shoulda-matchers#854]
I've just upgraded aasm gem to latest version and now I have a failing shoulda matcher (version 2.8.0) spec. The code is pretty standard, I have a `Bookmark` model which belongs to a user and a bookmarkable (polymorphic) item. A given user can only bookmark items once thus I have this spec:

```ruby
it { should validate_uniqueness_of(:user_id).scoped_to(:bookmarkable_id, :bookmarkable_type) }
```

Running this spec with latest aasm code raises an error. I tracked the error to [this line](https://github.com/aasm/aasm/blob/64a133407d271d66462082622b67017f60a72374/lib/aasm/persistence/active_record_persistence.rb#L137) in aasm code. The issue is that the bookmarkable item (passed in matcher by shoulda code) does not retain its original class. 

In my spec setup I create a Bookmark using a factory and matcher code uses that factory to compute values for assertion. My factory returns an instance of `Place` for bookmarkable while in some way the class of bookmarkable used in matcher is
```
class Shoulda::Matchers::ActiveRecord::Uniqueness::TestModels::Placf < ActiveRecord::Base
```
That name is likely generated by [this code](https://github.com/thoughtbot/shoulda-matchers/blob/8253d4b4c9b5489ea003784e638e04db353f6250/lib/shoulda/matchers/active_record/uniqueness/test_model_creator.rb), however I don't know its purpose.

In any case I think that test models generated by your matcher should behave like original one, so they should return original class when `#class` is called on their instance.

**Comment by fabn** [comment]
For the record I temporarily fixed the issue by adding this code in spec setup.

```ruby
allow_any_instance_of(AASM::Persistence::ActiveRecordPersistence::InstanceMethods).
  to receive(:aasm_ensure_initial_state).and_return(true)
```

**Comment by mcmire** [comment]
Can you post the exception that was raised along with the backtrace?

**Comment by fabn** [comment]
Of course, here it is

```
Failures:

  1) Bookmark Uniqueness constraint should require case sensitive unique value for user_id scoped to bookmarkable_id, bookmarkable_type
     Failure/Error: it { should validate_uniqueness_of(:user_id).scoped_to(:bookmarkable_id, :bookmarkable_type) }

     NoMethodError:
       undefined method `keys' for nil:NilClass
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/aasm-4.5.0/lib/aasm/persistence/active_record_persistence.rb:138:in `aasm_ensure_initial_state'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/aasm-4.5.0/lib/aasm/persistence/active_record_persistence.rb:36:in `block in included'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `instance_exec'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `block in make_lambda'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:228:in `call'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `block in call'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `each'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_initialize_callbacks'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/core.rb:312:in `init_with'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/persistence.rb:69:in `instantiate'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/querying.rb:50:in `block (2 levels) in find_by_sql'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/result.rb:51:in `block in each'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/result.rb:51:in `each'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/result.rb:51:in `each'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/querying.rb:50:in `map'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/querying.rb:50:in `block in find_by_sql'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/querying.rb:49:in `find_by_sql'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/statement_cache.rb:107:in `execute'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/associations/singular_association.rb:53:in `get_records'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/associations/singular_association.rb:57:in `find_target'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/associations/association.rb:138:in `load_target'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/associations/association.rb:53:in `reload'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/associations/singular_association.rb:9:in `reader'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/associations/builder/association.rb:115:in `bookmarkable'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activemodel-4.2.5/lib/active_model/validator.rb:149:in `block in validate'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activemodel-4.2.5/lib/active_model/validator.rb:148:in `each'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activemodel-4.2.5/lib/active_model/validator.rb:148:in `validate'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/validations/presence.rb:5:in `validate'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:455:in `public_send'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:455:in `block in make_lambda'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `call'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `block in simple'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `block in call'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `each'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activemodel-4.2.5/lib/active_model/validations.rb:398:in `run_validations!'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activemodel-4.2.5/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activemodel-4.2.5/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activemodel-4.2.5/lib/active_model/validations.rb:337:in `valid?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.5/lib/active_record/validations.rb:58:in `valid?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validator.rb:97:in `validation_errors'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validator.rb:77:in `collect_messages'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validator.rb:40:in `messages'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validator.rb:48:in `has_messages?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:277:in `has_messages?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:273:in `errors_match?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:224:in `block in matches?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:220:in `each'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:220:in `none?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:220:in `matches?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validation_matcher.rb:43:in `allows_value_of'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:381:in `block in validate_after_scope_change?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:371:in `each'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:371:in `all?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:371:in `validate_after_scope_change?'
     # /Users/fabio/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:247:in `matches?'
     # ./spec/models/bookmark_spec.rb:13:in `block (3 levels) in <top (required)>'
```

Is caused by [this line](https://github.com/aasm/aasm/blob/64a133407d271d66462082622b67017f60a72374/lib/aasm/persistence/active_record_persistence.rb#L138) triggered in an after_initialize callback because it uses object class as key.

And here's a minimal AR class to reproduce this error

```ruby
class Bookmark < ActiveRecord::Base
  belongs_to :user, required: true, touch: true
  belongs_to :bookmarkable, polymorphic: true, required: true
  # Prevent users to add same bookmark twice
  validates_uniqueness_of :user_id, scope: [:bookmarkable_id, :bookmarkable_type]
end
```

However notice that AASM is not used in `Bookmark` class but is used in another class whose instance is assigned to bookmarkable property.
