### ISSUE TITLE
undefined method `attribute_setter' for nil:NilClass

### ISSUE THREAD

**Issue by Draiken** [thoughtbot/shoulda-matchers#904]
Hello!

I'm receiving an error when a validation fails with the `validates_inclusion_of` matcher. If the validation is present, everything is fine, but without it when building the failure message you get this error:

```
NoMethodError:
       undefined method `attribute_setter' for nil:NilClass
     # ./.gem/ruby/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:405:in `failure_message'
     # ./.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/try.rb:77:in `public_send'
     # ./.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/try.rb:77:in `try!'
     # ./.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/try.rb:63:in `try'
     # ./.gem/ruby/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:129:in `failure_reason'
     # ./.gem/ruby/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:56:in `block in failure_message'
     # ./.gem/ruby/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:55:in `tap'
     # ./.gem/ruby/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:55:in `failure_message'
     # ./spec/lib/models/address_spec.rb:22:in `block (2 levels) in <module:Models>'
```

My class and spec look close to this:

```
class Thing
  include Virtus.model
  include ActiveModel::Model

  ARRAY = ["value"] 

  attribute :thing, String
end

RSpec.describe Thing do
  it { is_expected.to validate_inclusion_of(:thing).in_array(Thing::ARRAY) }
end
```

I am using active model outside of rails, configuring `Shoulda` to integrate with `RSpec` and `ActiveModel`. Ruby version is 2.3.0 and ActiveModel version is 4.2.5.1

Maybe this is an incompatibility with Virtus that I'm not aware of?

Thanks

**Comment by halilim** [comment]
I'm getting the same error with a regular Active Record association:

```ruby
describe ClassifiedProperty do
  it "should validate that :option is one of :property's options" do
    is_expected.to(
      validate_inclusion_of(:property_option_id)
        .in_array(subject.property.option_ids)
        .allow_nil
    )
  end
end
````
And similarly, it's gone when the validation is in place.

**Comment by joshuarh** [comment]
Encountering the same issue.

**Model:**
```
describe Activity do
  it { should validate_inclusion_of(:type).in_array([ 'video' ]) }
end
```

**Schema**:
```
  create_table "activities", force: :cascade do |t|
    t.string   "name",        null: false
    t.integer  "session_id",  null: false
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
    t.string   "description"
    t.string   "type",        null: false
  end
```

**Error**:
```
Failures:

  1) Activity should validate that :type is ‹"video"›
     Failure/Error: it { should validate_inclusion_of(:type).in_array(ActivityTypes.all) }
     
     NoMethodError:
       undefined method `attribute_setter' for nil:NilClass
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:405:in `failure_message'
     # ./.bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/core_ext/object/try.rb:17:in `public_send'
     # ./.bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/core_ext/object/try.rb:17:in `try!'
     # ./.bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/core_ext/object/try.rb:6:in `try'
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:129:in `failure_reason'
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:56:in `block in failure_message'
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:55:in `tap'
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:55:in `failure_message'
     # ./spec/models/activity_spec.rb:12:in `block (2 levels) in <top (required)>'
```

**Comment by joshuarh** [comment]
This validation also cannot be used at all if the validation is on an abstract parent:

**Shared Examples**:
```
shared_examples_for 'an activity' do
  it { should validate_inclusion_of(:type).in_array([ 'video' ]) }
end
```

**Spec**:
```
describe Activity::Video do
  it_behaves_like 'an activity'
end
```

**Models**:

```
class Activity < ApplicationRecord
  self.abstract_class = true
  validates :type, inclusion: [ 'video' ]
end
```

```
class Activity::Video < Activity
  self.table_name = 'activities'

  def type
    'video'
  end
end
```

**Error**:

```
Failures:

  1) Activity::Video behaves like an activity should validate that :type is ‹"video"›
     Failure/Error: it { should validate_inclusion_of(:type).in_array([ 'video' ]) }
     
     NoMethodError:
       undefined method `attribute_setter' for nil:NilClass
     Shared Example Group: "an activity" called from ./spec/models/activity/video_spec.rb:2
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:405:in `failure_message'
     # ./.bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/core_ext/object/try.rb:17:in `public_send'
     # ./.bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/core_ext/object/try.rb:17:in `try!'
     # ./.bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/core_ext/object/try.rb:6:in `try'
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:129:in `failure_reason'
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:56:in `block in failure_message'
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:55:in `tap'
     # ./.bundle/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:55:in `failure_message'
     # ./spec/models/activity/activity_shared_spec.rb:8:in `block (2 levels) in <top (required)>'
```

**Comment by meoooh** [comment]
I have same issue. I'm using shoulda-matcher 3.1.1

**Comment by jiggneshhgohel** [comment]
I am facing the same error when specifying `with_message` qualifier with a regex containing wildcard character matcher or an interpolation:

```
     NoMethodError:
       undefined method `attribute_setter' for nil:NilClass
```

Details below:

```
class CheckinContact < ActiveRecord::Base
  SUPPORTED_CONTACT_LEVELS = %w( primary secondary )

  belongs_to :user

  validates_presence_of :contact_level, :user
  validates_inclusion_of :contact_level, in: SUPPORTED_CONTACT_LEVELS, message: "is unacceptable. It can be either one of the following: #{SUPPORTED_CONTACT_LEVELS}"
end
```

```
require 'rails_helper'

RSpec.describe CheckinContact, type: :model do
  it { should respond_to(:contact_level) }

  it { should belong_to(:user) }

  it { should validate_presence_of(:contact_level) }
  it { should validate_presence_of(:user) }

  it {
    supported_contact_levels = CheckinContact::SUPPORTED_CONTACT_LEVELS
    should validate_inclusion_of(:contact_level).in_array(supported_contact_levels).with_message(/.* is unacceptable\. It can be either one of the following: #{supported_contact_levels}/)
  }
end
```


```
CheckinContact
  should respond to #contact_level
  should belong to user
  should validate that :contact_level cannot be empty/falsy
  should validate that :user cannot be empty/falsy
  should validate that :contact_level is either ‹"primary"› or ‹"secondary"›, producing a custom validation error on failure (FAILED - 1)

Failures:

  1) CheckinContact should validate that :contact_level is either ‹"primary"› or ‹"secondary"›, producing a custom validation error on failure
     Failure/Error: should validate_inclusion_of(:contact_level).in_array(supported_contact_levels).with_message(/.* is unacceptable\. It can be either one of the following: #{supported_contact_levels}/)
     
     NoMethodError:
       undefined method `attribute_setter' for nil:NilClass
     # .../gems/shoulda-matchers-3.1.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:405:in `failure_message'
     # .../gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/try.rb:77:in `public_send'
     # .../gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/try.rb:77:in `try!'
     # .../gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/try.rb:63:in `try'
     # .../gems/shoulda-matchers-3.1.0/lib/shoulda/matchers/active_model/validation_matcher.rb:129:in `failure_reason'
     # .../gems/shoulda-matchers-3.1.0/lib/shoulda/matchers/active_model/validation_matcher.rb:56:in `block in failure_message'
     # .../gems/shoulda-matchers-3.1.0/lib/shoulda/matchers/active_model/validation_matcher.rb:55:in `tap'
     # .../gems/shoulda-matchers-3.1.0/lib/shoulda/matchers/active_model/validation_matcher.rb:55:in `failure_message'
     # ./spec/models/checkin_contact_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:61:in `block (3 levels) in <top (required)>'
     # .../gems/database_cleaner-1.5.1/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # .../gems/database_cleaner-1.5.1/lib/database_cleaner/base.rb:92:in `cleaning'
     # .../gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # .../gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:87:in `call'
     # ../gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:60:in `block (2 levels) in <top (required)>'

```

I have confirmed that using the regex without any wildcard matcher or interpolation the spec passes.

```
  it {
    supported_contact_levels = CheckinContact::SUPPORTED_CONTACT_LEVELS
    should validate_inclusion_of(:contact_level).in_array(supported_contact_levels).with_message(/is unacceptable\. It can be either one of the following/)
  }
```
